## Site
site_name: SRE / DevOps Taiwan 讀書會
site_url: 'https://study-area.sre.tw/'
repo_url: 'https://github.com/cross-community/study-area-docs'
docs_dir: 'docs'

# Copyright
#copyright: 'Copyright &copy; 2016 - 2017 Martin Donath'

## Navigator
nav:
  - "讀書會緣由": index.md
  - "導讀：Site Reliability Engineering":
    - "緒論、第一章": "01_SRE/CH01.md"
    - "第二、三、四章": "01_SRE/CH02-04.md"
    - "第五、六、七章": "01_SRE/CH05-07.md"
    - "第八～十一章": "01_SRE/CH08-11.md"
    - "第十二～十五章": "01_SRE/CH12-15.md"
    - "第十六～十八章": "01_SRE/CH16-18.md"
    - "第十九～廿一章": "01_SRE/CH19-21.md"
    - "第廿二章": "01_SRE/CH22.md"
    - "第廿三、廿四章": "01_SRE/CH23-24.md"
    - "第廿五章": "01_SRE/CH25.md"
    - "第廿六、廿八章": "01_SRE/CH26-28.md"
    - "第廿七章": "01_SRE/CH27.md"
    - "第卅、卅一章": "01_SRE/CH30-31.md"
    - "第卅二～卅四章": "01_SRE/CH32-34.md"
  - "SRE 經典好文": "Articles.md"
  - "事件處理案例": "Incidents.md"
  - "相關活動分享": "Events.md"
  - "----------": separator.md
  - "讀書會 Round 2": 02_CD.md
  - "導讀：Continuous Delivery":
    - "第一章 軟體交付的問題": "02_CD/CH01.md"
    - "第二章 設置管理": "02_CD/CH02.md"
    - "第三章 持續整合": "02_CD/CH03.md"
    - "第四章 測試策略的實現": "02_CD/CH04.md"
    - "第五章 部署流水線": "02_CD/CH05.md"
    - "第六章 建置與佈署腳本化": "02_CD/CH06.md"
    - "第七章 提交階段": "02_CD/CH07.md"
    - "第八章 驗收測試階段": "02_CD/CH08.md"
    - "第九章 非功能需求測試": "02_CD/CH09.md"
    - "第十章 應用程式的部署與發佈": "02_CD/CH10.md"
    - "第十一章 管理基礎設施與環境": "02_CD/CH11.md"
    - "第十二章 資料管理": "02_CD/CH12.md"
    - "第十三章 元件相依性管理": "02_CD/CH13.md"
    - "第十四章 版本控制進階": "02_CD/CH14.md"
    - "第十五章 持續交付管理": "02_CD/CH15.md"
  - "----------": separator.md
  - "讀書會 Round 3":
    - "春酒與選書": 03_K8s.md
    - "讀書會行程": "03_K8s/Schedule.md"
    - "讀書會 QA": "03_K8s/QA.md"
#    - "相見歡": "03_K8s/0314.md"
  - "----------": separator.md
  - "導讀 Guideline": GuideLine.md
  - "----------": separator.md
  - "Change Log": "ChangeLog.md"
  - "記事": "notes.md"

##
# Theme: material
theme:
#  name: readthedocs # default
  name: material
  palette:
    primary: 'light blue'
    accent: 'indigo'
  logo:
    icon: 'cloud'
  language: 'zh-TW'
  feature:
    tabs: false

## Custom
#extra_css:
#  - 'stylesheets/extra.css'

extra:
  manifest: 'manifest.webmanifest'
  # https://squidfunk.github.io/mkdocs-material/getting-started/#adding-social-links
  social:
    - type: facebook
      link: https://www.facebook.com/groups/sre.taiwan/
    - type: github
      link: https://github.com/cross-community/study-area-docs/
  disqus: 'sre-tw'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true


google_analytics: ['UA-135928551-1', 'study-area.sre.tw']
